version: '3.8'
services:
  frontend:
    build: ./frontend
    image: frontend:latest
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    command: npm run dev
  backend:
    build: ./backend
    image: backend:latest
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
    command: npm run dev
